# Using prezto to customise Zsh.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.bash_aliases

# Copied a hacked version of agnoster for oh-my-zsh; it's compact and
source "${HOME}/.zprezto/prompt.zsh"
export PS1="%{%f%b%k%}$(build_prompt)"
